---
title: "Process 3D Print Data"
author: "Sam Coleman"
date: "3/24/2022"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(chron)
library(viridis)
```

```{r define-theme}
theme_common <- function() {
  theme_minimal() %+replace%
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_text(margin = margin(4, 4, 4, 4), size = 16),
    axis.title.y = element_text(margin = margin(4, 4, 4, 4), size = 16, angle = 90),
    legend.title = element_text(size = 16),
    legend.text = element_text(size = 12),
    strip.text.x = element_text(size = 12),
    strip.text.y = element_text(size = 12),
    panel.grid.major = element_line(color = "grey90"),
    panel.grid.minor = element_line(color = "grey90"),
    aspect.ratio = 10/16,
    plot.margin = unit(c(t = +0, b = +0, r = +0, l = +0), "cm"),
    plot.title = element_text(size = 18),
    # plot.title.position = "plot",
    plot.subtitle = element_text(size = 16),
    plot.caption = element_text(size = 12)
  )
}
```


```{r load-data}
df_curr_raw <- read_csv(file = "data/3d_curr.csv")
df_old_raw <- read_csv(file = "data/3d_old.csv")
```


```{r}
df_both_raw <-
  bind_rows(df_curr_raw,df_old_raw)


df_both <- 
  df_both_raw %>% 
  mutate(
    print_mass = str_extract(print_mass_grams, "\\d+"), # extract just mass from print mass
    class = tolower(class), #make class lowercase
    printer = tolower(printer)
  ) %>% 
  #separate into date and time
  separate(timestamp, c("date", "time"), sep = " ", remove = FALSE) %>% 
  transform(
    date = as.Date(date),
    time = chron(time = time),
    print_mass = as.numeric(print_mass)
  )

printers <- c("himalia", "elera", "ganymede", "callisto", "thebe", "themisto",
              "io", "metis", "sinope", "dia", "europa", "queue", 
              "valetudo", "amalthea", NA)

df_both <-
  df_both %>% 
  mutate (
    printer = str_replace(printer, "hima.*", "himalia"),
    printer = str_replace(printer, "elar.*", "elera"),
    printer = str_replace(printer, "gany.*", "ganymede"),
    printer = str_replace(printer, "themi.*", "themisto"),
    printer = str_replace(printer, "cal.*", "callisto"),
    printer = str_replace(printer, "theb.*", "thebe"),
    printer = str_replace(printer, "io.*", "io"),
    printer = str_replace(printer, "met.*", "metis"),
    printer = str_replace(printer, "sin.*", "sinope"),
    printer = str_replace(printer, "dia.*", "dia"),
    printer = str_replace(printer, "euro.*", "europa"),
    printer = str_replace(printer, ".*que.*", "queue"),
    printer = str_replace(printer, "val.*", "valetudo"),
    printer = str_replace(printer, ".*thea.*", "amalthea"),
    printer = ifelse(printer %in% printers, printer, "other")
  )

#unique(df_curr$class)

# Standardize each class to ensure pie/principles of integrated engineering are the same/pieeeeeee are the same
df_both <-
  df_both %>% 
  mutate (
    class = str_replace(class, "pie.*", "pie"),
    class = str_replace(class, "dfm|.*manufact.*", "dfm"),
    class = str_replace(class, ".*scope.*", "scope"),
    class = str_replace(class, ".*indep.*|is.*", "is"),
    class = str_replace(class, ".*nat.*|.*nt.*", "desnat"),
    class = str_replace(class, ".*renewable.*", "renewable energy"),
    class = str_replace(class, ".*eec.*", "eec"),
    class = str_replace(class, ".*proto.*", "mech proto"),
    class = str_replace(class, ".*qea.*", "qea"),
    class = str_replace(class, ".*research.*|.*lair.*", "research"),
    class = str_replace(class, ".*market.*|p&.*|p[[:space:]]&.*", "p&m"),
    class = str_replace(class, ".*sust.*", "sustdes"),
    class = str_replace(class, ".*robos.*", "robosys"),
    class = str_replace(class, ".*dbf.*|design[[:space:]]bu.*", "dbf"),
    class = factor(
      class,
      levels = c("pie", "dfm", "scope", "is", "desnat", "renewable energy", "eec", "mech proto", "qea", "research", "p&m", "sustdes", 
        "robosys", "dbf")
    ),
   reason_print = str_replace(reason_print, "Class Project", "Class Project/Research"), #combine since Class Project/Research was created in middle of survey
   reason_print = factor(
     reason_print,
     levels = c("Class Project/Research", "Personal Project", "Project Team/Club", "Test Piece")
   )
  )

```

```{r}
df_both %>% 
  group_by(class) %>% 
  summarize(
    num_class = length(class)
  ) %>% 
  filter(
    !is.na(class)
  ) %>% 
  ggplot(aes(x = reorder(class, -num_class), y = num_class)) +
  geom_col() +
  #theme_common() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("Class") +
  ylab("Count")
```

```{r}
df_both %>% 
  count(reason_print) %>% 
  filter(!is.na(reason_print)) %>%
  ggplot(aes(x = reorder(reason_print, -n), y = n)) +
  geom_col() +
  xlab("Reason") +
  ylab("Count") +
  ggtitle("Reasons for Prints")
  
```
```{r}
df_both %>% 
  group_by(date) %>% 
  mutate(
    num_per_date = length(date)
  ) %>% 
  ggplot(aes(x = date, y = num_per_date)) +
  geom_point() +
  geom_line() +
  ggtitle("Daily Prints")

  
  
```
```{r}
df_both %>% 
  filter(class == "pie") %>%
  group_by(date) %>%
  mutate(
    num_per_date = length(date),
    mass_per_date = sum(print_mass, na.rm = TRUE)
  ) %>%
  ggplot(aes(x = date, fill = mass_per_date, group = interaction(date, mass_per_date))) +
  geom_bar() +
  scale_fill_gradient(low = "green", high = "red") +
  ggtitle("Daily Prints for PIE")

```

```{r}
df_both %>% 
  filter(class == "pie") %>%
  group_by(date) %>%
  mutate(
    num_per_date = length(date),
    mass_max_date = max(print_mass, na.rm = TRUE)
  ) %>%
  ggplot(aes(x = date, fill = mass_max_date, group = interaction(date, mass_max_date))) +
  geom_bar() +
  scale_fill_gradient(low = "green", high = "red") +
  ggtitle("Daily Prints for PIE")
```


```{r}
df_both %>% 
  ggplot(aes(x = print_mass)) +
  geom_histogram() 
```

```{r}
df_both %>% 
  group_by(date) %>% 
  mutate(
    num_per_date = length(date)
  ) %>% 
  ggplot(aes(x = date, y = num_per_date)) +
  #geom_point() +
  #geom_line() +
  geom_segment(aes(date,num_per_date,xend=date,yend=0), size=0.05) +
  geom_point() +
  ggtitle("Daily Prints")
```
```{r}
# df_old %>% 
#   group_by(date) %>% 
#   mutate(
#     mass_per_date = sum(print_mass, na.rm = TRUE)
#   ) %>% 
#   ggplot(aes(x = date, y = mass_per_date)) +
#   #geom_point() +
#   geom_line() +
#   ggtitle("Daily Prints")
```

```{r}
df_both %>% 
  group_by(date) %>% 
  mutate(
    date_avg = mean(print_mass, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = date, y = date_avg)) +
  #geom_point() +
  geom_line() 
```

```{r}
df_both %>% 
  filter(printer != "other") %>%
  group_by(printer) %>% 
  mutate(
    num_per_printer = length(printer)
  ) %>% 
  ggplot(aes(x = printer, y = num_per_printer)) +
  #geom_point() +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

```

```{r}
df_both %>% 
  group_by(printer) %>% 
  
  ggplot(aes(x = printer)) +
  #geom_point() +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

```
```{r}
unique(df_both$printer)



```

```{r}
df_both %>%
  mutate(
    time=hms(as.character(time)),
    time = hour(time)
  ) %>%
  ggplot() +
  geom_histogram(aes(x=time),binwidth = 1)
```

```{r}
df_both %>% 
  summarize(
    total_mass = sum(print_mass, na.rm = TRUE)
  )
```
```{r}
# mass per month
df_both %>% 
  group_by(month = lubridate::floor_date(date, "month")) %>% 
  summarize(mass_per_month = sum(print_mass, na.rm = TRUE)) %>%   
  mutate(
    month_12 = month(month),
    month_12 = factor(
       month_12,
       levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12")
     ) 
  ) %>% 
  ggplot(aes(x = month, y = mass_per_month, fill = month_12)) +
  geom_col() +
  scale_fill_discrete(name = "Month", labels = c("Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"))
  #scale_color_manual(labels = c("Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"))
```
```{r}
df_both %>% 
  group_by(month = lubridate::floor_date(date, "month")) %>% 
  summarize(
    mean_mass = mean(print_mass, na.rm = TRUE),
    median_mass = median(print_mass, na.rm = TRUE),
    max_mass = max(print_mass, na.rm = TRUE)
  ) %>% 
   mutate(
    month_12 = month(month),
    month_12 = factor(
       month_12,
       levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12")
     ) 
  ) %>%
  ggplot(aes(x = month, y = mean_mass, fill = month_12)) +
  geom_col() +
  geom_hline(yintercept = 40.1, linetype = "dashed") +
  scale_fill_discrete(name = "Month", labels = c("Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"))

```

```{r}
df_both %>% 
  group_by(month = lubridate::floor_date(date, "month")) %>% 
  summarize(
    mean_mass = mean(print_mass, na.rm = TRUE),
    median_mass = median(print_mass, na.rm = TRUE),
    max_mass = max(print_mass, na.rm = TRUE)
  ) %>% 
   mutate(
    month_12 = month(month),
    month_12 = factor(
       month_12,
       levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12")
     ) 
  ) %>%
  ggplot(aes(x = month, y = max_mass, fill = month_12)) +
  geom_col() +
  scale_fill_discrete(name = "Month", labels = c("Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"))

```

```{r}

```
```{r}
df_both %>% 
  group_by(month = lubridate::floor_date(date, "month")) %>% 
   mutate(
    month_12 = month(month),
    month_12 = factor(
       month_12,
       levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12")
     ) 
  ) %>%
  ggplot(aes(x = month, y = print_mass, fill = month_12, group = month)) +
  # geom_col()
  geom_boxplot(na.rm = TRUE) +
  scale_y_log10() +
  scale_fill_discrete(name = "Month", labels = c("Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"))
```
```{r}
df_both %>% 
  group_by(month = lubridate::floor_date(date, "month")) %>% 
   mutate(
    month_12 = month(month),
    month_12 = factor(
       month_12,
       levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12")
     ) 
  ) %>%
  ggplot(aes(x = month, y = print_mass, fill = month_12, group = month)) +
  # geom_col()
  geom_boxplot(na.rm = TRUE) +
  scale_fill_discrete(name = "Month", labels = c("Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"))
```

```{r}
df_both %>% 
  group_by(class) %>% 
  summarize(
    num_class = length(class),
    mean_mass = mean(print_mass, na.rm = TRUE)
  ) %>% 
  filter(
    !is.na(class)
  ) %>% 
  ggplot(aes(x = reorder(class, -num_class), y = num_class, fill = mean_mass)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("Class") +
  ylab("Count") +
  scale_fill_viridis()
```

```{r}
df_both %>% 
  group_by(date) %>% 
  summarize(
    num_per_day = length(date)
  ) %>% 
  ggplot(aes(x = date, y = num_per_day)) +
  geom_point() +
  geom_smooth() +
  scale_x_date(labels = scales::date_format("%b"), 
               breaks = "1 month") +
  facet_wrap(. ~ lubridate::floor_date(date, "year"), scale = "free_x") +
   theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust = 1))
```

```{r}
# df_both %>% 
#   group_by(date) %>% 
#   summarize(
#     num_per_day = length(date)
#   ) %>% 
#   mutate (
#     year = substring(date, 1, 4),
#     month = substring(date, 6, 10),
#     #month = as.Date(month, format = "%m-%d")
#   )  %>% 
#   ggplot(aes(x = month, y = num_per_day)) +
#   geom_smooth(aes(group = year, color = year)) +
#   scale_x_date(labels = scales::date_format("%b"), 
#                breaks = "1 month")

df_both %>% 
  mutate (
    year = substring(date, 1, 4),
    month = substring(date, 6, 10),
    #month = as.Date(month, format = "%m-%d")
  ) %>% 
  group_by(year, month) %>% 
  summarize(
    num_per_day = length(month)
  ) %>% 
  ggplot(aes(x = as.Date(month, "%m-%d"), y = num_per_day, group = year, color = year)) +
  geom_line() +
  scale_x_date(labels = scales::date_format("%b"), breaks = "1 month") +
  xlab("Date") +
  ylab("Number Prints per Day")

df_both %>% 
  mutate (
    year = substring(date, 1, 4),
    month = substring(date, 6, 10),
    #month = as.Date(month, format = "%m-%d")
  ) %>% 
  group_by(year, month) %>% 
  summarize(
    num_per_day = length(month)
  ) %>% 
  ggplot(aes(x = as.Date(month, "%m-%d"), y = num_per_day, group = year, color = year)) +
  geom_smooth(span = 1) +
  scale_x_date(labels = scales::date_format("%b"), breaks = "1 month") +
  xlab("Date") +
  ylab("Number Prints per Day")


```

