---
title: "General Shop Tools"
author: "Sam Coleman"
date: "3/27/2022"
output: 
  github_document:
    toc: true
---
```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl) 
library(viridis)
library(stringr)
```

```{r}
theme_common <- function() {
  theme_minimal() %+replace%
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_text(margin = margin(4, 4, 4, 4), size = 16),
    axis.title.y = element_text(margin = margin(4, 4, 4, 4), size = 16, angle = 90),
    legend.title = element_text(size = 16),
    legend.text = element_text(size = 12),
    strip.text.x = element_text(size = 12),
    strip.text.y = element_text(size = 12),
    panel.grid.major = element_line(color = "grey90"),
    panel.grid.minor = element_line(color = "grey90"),
    aspect.ratio = 10/16,
    plot.margin = unit(c(t = +0, b = +0, r = +0, l = +0), "cm"),
    plot.title = element_text(size = 18),
    # plot.title.position = "plot",
    plot.subtitle = element_text(size = 16),
    plot.caption = element_text(size = 12)
  )
}
```


```{r load-data}
col_names <-
  c(
    "training",
    "sp22_signup",
    "sp22_complete",
    "sp22_comp_rate",
    "fa21_signup",
    "fa21_complete",
    "fa21_comp_rate",
    "sp20_signup",
    "sp20_complete",
    "sp20_comp_rate",
    "fa19_signup",
    "fa19_complete",
    "fa19_comp_rate",
    "sp19_signup",
    "sp19_complete",
    "sp19_comp_rate",
    "fa18_signup",
    "fa18_complete",
    "fa18_comp_rate",
    "sp18_signup",
    "sp18_complete",
    "sp18_comp_rate",
    "fa17_signup",
    "fa17_complete",
    "fa17_comp_rate",
    "sp17_signup",
    "sp17_complete",
    "sp17_comp_rate",
    "fa16_signup",
    "fa16_complete",
    "fa16_comp_rate",
    "total_signup",
    "total_complete",
    "total_comp_rate"
  )

df_raw <- read_excel("data/edited_shopTrainingSummary.xlsx", sheet = 2, col_names = col_names, skip = 1)
df_raw
# create total row without green
# make tidy
# df_tidy <-
#   df_raw %>% 
#   pivot_longer(cols = !"training", names_to = "sem_stat", values_to = "stat") %>% 

df_tidy <-
  df_raw %>% 
  pivot_longer(cols = !"training", names_to = "sem", values_to = "val")

df_tidy
```

```{r}
df_raw %>% 
  filter(
    !training %in% c("Total", "Green", "total_not_green"),
    !is.na(training)
  ) %>% 
  ggplot(aes(x = reorder(training, -total_signup), y = total_signup, fill = total_comp_rate)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_viridis(name = "total completion rate") +
  xlab("Training") +
  ylab("Total Signup Since Fall 2016")
  
```
```{r}
df_raw %>% 
  filter(
    !training %in% c("Total", "Green"),
    !is.na(training)
  ) %>% 
  ggplot(aes(x = reorder(training, -total_comp_rate), y = total_signup, fill = total_comp_rate)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_viridis(name = "total completion rate") +
  xlab("Training") +
  ylab("Total Signup Since Fall 2016")
```
```{r}
df_raw %>% 
  filter(
    !training %in% c("Total", "Green", "total_not_green"),
    !is.na(training)
  ) %>% 
  mutate(
    fully_complete = total_complete
  ) %>% 
  pivot_longer(names_to = "stat", values_to = "val_stat", cols = c("total_signup", "total_complete")) %>% 
  ggplot(aes(x = reorder(training, -fully_complete), y = val_stat, fill = stat)) +
  geom_col(position = "dodge") +
  theme_common() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  #scale_fill_viridis(name = "total completion rate") +
  xlab("Training") +
  ylab("Total Since Fall 2016") +
  scale_fill_discrete(name = "")
```

```{r}
# df_raw %>% 
#   filter(training == "3D Printing") %>% 
#   pivot_longer(names_to = "stat", values_to = "val_stat", cols = c(ends_with("complete"), ends_with("signup"), ends_with("rate"))) %>% 
#   filter(!is.na(val_stat)) %>% 
#   ggplot(aes(x = stat, y = val_stat, fill)) +
#   geom_col() +
#     theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

#TODO make graph in right order
df_raw %>% 
  filter(training %in% c("3D Printing", "total_not_green")) %>% 
  select("training", ends_with("complete")) %>% 
  pivot_longer(
    names_to = "complete", 
    values_to = "val_stat", 
    cols = c(
    "sp22_complete",
    "fa21_complete",
    "sp20_complete",
    "fa19_complete",
    "sp19_complete",
    "fa18_complete",
    "sp18_complete",
    "fa17_complete",
    "sp17_complete",
    "fa16_complete",
    "total_complete")
  ) %>% 
  filter(!is.na(val_stat), complete != "total_complete", complete %in% c("sp22_complete", "fa21_complete", "sp20_complete", "fa19_complete")) %>% 
  group_by(complete)  
  mutate(
    perc = sum(val_stat)
  ) %>% 
  #ungroup() %>% 
  mutate(
    perc = val_stat / perc,
    complete = factor(complete, levels = c("fa19_complete", "sp20_complete", "fa21_complete", "sp22_complete"), ordered = TRUE)
  ) %>% 
  filter(training == "3D Printing") %>% 
  # pivot_wider(names_from = "complete", values_from = "val_stat") %>% 
  # add_row(
  #   perc = 
  # )
  ggplot(aes(x = complete, y = val_stat, fill = perc)) +
  geom_col() +
  theme_common() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("Semester") +
  ylab("Count 3D Print Completed Trainings") +
  scale_fill_continuous(name = "Perc of completed \ntrainings that were \n3D printer") +
  scale_x_discrete(labels = c("fa19", "sp20", "fa21", "sp22"))
  #scale_fill_viridis()
``` 
```{r}
df_3d_total <-
  tribble(
    ~semester, ~num_train, ~ratio,
    "fa19", 38, 38/410,
    "sp20", 7, 7/110,
    "fa21", 59, 59/459,
    "sp22", 24, 24/104
  ) %>% 
  mutate(
    semester = factor(semester, levels = c("fa19", "sp20", "fa21", "sp22"))
  )

df_3d_total %>% 
  ggplot(aes(x = semester, y = num_train, fill = ratio)) +
  geom_col() +
  theme_common() +
  xlab("Semester") +
  ylab("Count 3D Print Completed Trainings") +
  scale_fill_continuous(name = "Perc of completed \ntrainings \n(excl. Green) that were \n3D printer") +
  geom_text(aes(label = num_train), size = 3.2, vjust = -.2, colour = "black")
```



```{r}
df_tidy %>% 
  filter(
    training == "total_not_green", 
    str_detect(sem, "complete"),
    sem != "total_complete"
  ) %>% 
  mutate(
    sem = factor(sem, levels = c("fa16_complete", "sp17_complete", "fa17_complete", "sp18_complete", "fa18_complete", "sp19_complete", "fa19_complete", "sp20_complete", "fa21_complete", "sp22_complete"))
  ) %>% 
  ggplot(aes(x = sem, y = val)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme_common() +
  scale_x_discrete(labels = c("fa16", "sp17", "fa17", "sp18", "fa18", "sp19", "fa19", "sp20", "fa21", "sp22")) +
  xlab("Semester") +
  ylab("Count Completed Trainings (w/o Green)")
```
```{r fig.height=6, fig.width=6}

df_tidy %>% 
  filter(
    str_detect(sem, "complete"),
    training != "total_not_green",
    training != "Total",
    sem != "total_complete"
  ) %>% 
  mutate(
    val = ifelse(is.na(val), 0, val)
  ) %>% 
  filter(sem == "sp22_complete", val != 0) %>% 
  ggplot(aes(x = reorder(training, -val), y = val, fill = training)) +
  geom_col() +
  theme_common() +
  ggtitle("Trainings Spring 2022") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  geom_text(aes(label = val), size = 3.2, vjust = -.2, colour = "black") +
  labs(x = "Training", y = "Number Completed") 
 
# 
# # Basic piechart
# ggplot(data, aes(x="", y=value, fill=group)) +
#   geom_bar(stat="identity", width=1, color="white") +
#   coord_polar("y", start=0) +
#   
#   theme_void() # remove background, grid, numeric labels
```

